### ISSUE TITLE
Change shared workflows to be only used by trusted internal workflows.

### ISSUE THREAD

**Issue by KalebCoberly** [crickets-and-comb/shared#38]
There are points of code injection that do not pose a direct risk to the organization, but that malicious actors could use as a threat vector to trick others into using our workflows in a way that makes them vulnerable.

Rather than validating all user input and environmental variables, we need to add a trusted workflow list to all workflow call blocks:

```
on:
  workflow_call:
    inputs:
      ...
    secrets:
      ...
    required_workflows:
      - your-org/your-repo/.github/workflows/your-workflow.yml
```
